[versions]
agp = "9.0.0-alpha01"
emulatorwtf = "+"
kotlin = "2.2.21"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
rules = "1.6.1"
runner = "1.7.0"
uiautomator = "2.3.0"
baselineprofile = "1.4.1"
benchmarkMacroJunit4 = "1.4.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
emulatorwtf = { id = "wtf.emulator.gradle", version.ref = "emulatorwtf" }
integration-test-conventions = { id = "wtf.emulator.test.integration-test-conventions" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-core = { module = "androidx.test:core", version.ref = "rules" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitVersion" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }

