[versions]

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }

[libraries]
gradle-plugins-buildconfig = "com.github.gmazzo.buildconfig:plugin:5.3.5"
gradle-plugins-publish = "com.vanniktech:gradle-maven-publish-plugin:0.28.0"

agp = "com.android.tools.build:gradle:8.4.0"

gradle-api-v61 = "dev.gradleplugins:gradle-api:6.1.1"
gradle-api-v66 = "dev.gradleplugins:gradle-api:6.6"
gradle-api-v76 = "dev.gradleplugins:gradle-api:7.6"

semver4j = "com.vdurmont:semver4j:3.1.0"

json = "org.json:json:20240303"

commons-io = "commons-io:commons-io:2.16.1"

[bundles]

